In [49]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.linear_model import LinearRegression

In [50]:
cars=pd.read_csv("Z:\FA1\DataSets\Cars93.csv")
cars.head()

,Unnamed: 0,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
0,1,Acura,Integra,Small,12.9,15.9,18.8,25,31,None,...,5,177,102,68,37,26.5,11.0,2705,non-USA,Acura Integra
1,2,Acura,Legend,Midsize,29.2,33.9,38.7,18,25,Driver & Passenger,...,5,195,115,71,38,30.0,15.0,3560,non-USA,Acura Legend
2,3,Audi,90,Compact,25.9,29.1,32.3,20,26,Driver only,...,5,180,102,67,37,28.0,14.0,3375,non-USA,Audi 90
3,4,Audi,100,Midsize,30.8,37.7,44.6,19,26,Driver & Passenger,...,6,193,106,70,37,31.0,17.0,3405,non-USA,Audi 100
4,5,BMW,535i,Midsize,23.7,30.0,36.2,22,30,Driver only,...,4,186,109,69,39,27.0,13.0,3640,non-USA,BMW 535i

In [51]:
cars.isnull().sum()

Unnamed: 0             0
Manufacturer           0
Model                  0
Type                   0
Min.Price              0
Price                  0
Max.Price              0
MPG.city               0
MPG.highway            0
AirBags                0
DriveTrain             0
Cylinders              0
EngineSize             0
Horsepower             0
RPM                    0
Rev.per.mile           0
Man.trans.avail        0
Fuel.tank.capacity     0
Passengers             0
Length                 0
Wheelbase              0
Width                  0
Turn.circle            0
Rear.seat.room         2
Luggage.room          11
Weight                 0
Origin                 0
Make                   0
dtype: int64

In [52]:
cars["Luggage.room"].mean()

13.890243902439025

In [53]:
cars["Luggage.room"].fillna(cars["Luggage.room"].mean(),inplace=True)

In [54]:
cars["Luggage.room"].isnull().sum()

0

In [55]:
cars["Rear.seat.room"].fillna(cars["Rear.seat.room"].mean(),inplace=True)
cars["Rear.seat.room"].isnull().sum()

0

In [56]:
cars.drop(["Manufacturer","Model","Type","AirBags","Turn.circle","Passengers","Origin","Make"],axis=1,inplace=True)

In [57]:
cars.head()

,Unnamed: 0,Min.Price,Price,Max.Price,MPG.city,MPG.highway,DriveTrain,Cylinders,EngineSize,Horsepower,RPM,Rev.per.mile,Man.trans.avail,Fuel.tank.capacity,Length,Wheelbase,Width,Rear.seat.room,Luggage.room,Weight
0,1,12.9,15.9,18.8,25,31,Front,4,1.8,140,6300,2890,Yes,13.2,177,102,68,26.5,11.0,2705
1,2,29.2,33.9,38.7,18,25,Front,6,3.2,200,5500,2335,Yes,18.0,195,115,71,30.0,15.0,3560
2,3,25.9,29.1,32.3,20,26,Front,6,2.8,172,5500,2280,Yes,16.9,180,102,67,28.0,14.0,3375
3,4,30.8,37.7,44.6,19,26,Front,6,2.8,172,5500,2535,Yes,21.1,193,106,70,31.0,17.0,3405
4,5,23.7,30.0,36.2,22,30,Rear,4,3.5,208,5700,2545,Yes,21.1,186,109,69,27.0,13.0,3640

In [58]:
cars.drop(["DriveTrain","Cylinders","Man.trans.avail","Luggage.room","Rear.seat.room"],axis=1,inplace=True)
cars.head(30)

,Unnamed: 0,Min.Price,Price,Max.Price,MPG.city,MPG.highway,EngineSize,Horsepower,RPM,Rev.per.mile,Fuel.tank.capacity,Length,Wheelbase,Width,Weight
0,1,12.9,15.9,18.8,25,31,1.8,140,6300,2890,13.2,177,102,68,2705
1,2,29.2,33.9,38.7,18,25,3.2,200,5500,2335,18.0,195,115,71,3560
2,3,25.9,29.1,32.3,20,26,2.8,172,5500,2280,16.9,180,102,67,3375
3,4,30.8,37.7,44.6,19,26,2.8,172,5500,2535,21.1,193,106,70,3405
4,5,23.7,30.0,36.2,22,30,3.5,208,5700,2545,21.1,186,109,69,3640
5,6,14.2,15.7,17.3,22,31,2.2,110,5200,2565,16.4,189,105,69,2880
6,7,19.9,20.8,21.7,19,28,3.8,170,4800,1570,18.0,200,111,74,3470
7,8,22.6,23.7,24.9,16,25,5.7,180,4000,1320,23.0,216,116,78,4105
8,9,26.3,26.3,26.3,19,27,3.8,170,4800,1690,18.8,198,108,73,3495
9,10,33.0,34.7,36.3,16,25,4.9,200,4100,1510,18.0,206,114,73,3620
10,11,37.5,40.1,42.7,16,25,4.6,295,6000,1985,20.0,204,111,74,3935
11,12,8.5,13.4,18.3,25,36,2.2,110,5200,2380,15.2,182,101,66,2490
12,13,11.4,11.4,11.4,25,34,2.2,110,5200,2665,15.6,184,103,68,2785
13,14,13.4,15.1,16.8,19,28,3.4,160,4600,1805,15.5,193,101,74,3240
14,15,13.4,15.9,18.4,21,29,2.2,110,5200,2595,16.5,198,108,71,3195
15,16,14.7,16.3,18.0,18,23,3.8,170,4800,1690,20.0,178,110,74,3715
16,17,14.7,16.6,18.6,15,20,4.3,165,4000,1790,27.0,194,111,78,4025
17,18,18.0,18.8,19.6,17,26,5.0,170,4200,1350,23.0,214,116,77,3910
18,19,34.6,38.0,41.5,17,25,5.7,300,5000,1450,20.0,179,96,74,3380
19,20,18.4,18.4,18.4,20,28,3.3,153,5300,1990,18.0,203,113,74,3515
20,21,14.5,15.8,17.1,23,28,3.0,141,5000,2090,16.0,183,104,68,3085
21,22,29.5,29.5,29.5,20,26,3.3,147,4800,1785,16.0,203,110,69,3570
22,23,7.9,9.2,10.6,29,33,1.5,92,6000,3285,13.2,174,98,66,2270
23,24,8.4,11.3,14.2,23,29,2.2,93,4800,2595,14.0,172,97,67,2670
24,25,11.9,13.3,14.7,22,27,2.5,100,4800,2535,16.0,181,104,68,2970
25,26,13.6,19.0,24.4,17,21,3.0,142,5000,1970,20.0,175,112,72,3705
26,27,14.8,15.6,16.4,21,27,2.5,100,4800,2465,16.0,192,105,69,3080
27,28,18.5,25.8,33.1,18,24,3.0,300,6000,2120,19.8,180,97,72,3805
28,29,7.9,12.2,16.5,29,33,1.5,92,6000,2505,13.2,174,98,66,2295
29,30,17.5,19.3,21.2,20,28,3.5,214,5800,1980,18.0,202,113,74,3490

In [59]:
cars.head(30)

,Unnamed: 0,Min.Price,Price,Max.Price,MPG.city,MPG.highway,EngineSize,Horsepower,RPM,Rev.per.mile,Fuel.tank.capacity,Length,Wheelbase,Width,Weight
0,1,12.9,15.9,18.8,25,31,1.8,140,6300,2890,13.2,177,102,68,2705
1,2,29.2,33.9,38.7,18,25,3.2,200,5500,2335,18.0,195,115,71,3560
2,3,25.9,29.1,32.3,20,26,2.8,172,5500,2280,16.9,180,102,67,3375
3,4,30.8,37.7,44.6,19,26,2.8,172,5500,2535,21.1,193,106,70,3405
4,5,23.7,30.0,36.2,22,30,3.5,208,5700,2545,21.1,186,109,69,3640
5,6,14.2,15.7,17.3,22,31,2.2,110,5200,2565,16.4,189,105,69,2880
6,7,19.9,20.8,21.7,19,28,3.8,170,4800,1570,18.0,200,111,74,3470
7,8,22.6,23.7,24.9,16,25,5.7,180,4000,1320,23.0,216,116,78,4105
8,9,26.3,26.3,26.3,19,27,3.8,170,4800,1690,18.8,198,108,73,3495
9,10,33.0,34.7,36.3,16,25,4.9,200,4100,1510,18.0,206,114,73,3620
10,11,37.5,40.1,42.7,16,25,4.6,295,6000,1985,20.0,204,111,74,3935
11,12,8.5,13.4,18.3,25,36,2.2,110,5200,2380,15.2,182,101,66,2490
12,13,11.4,11.4,11.4,25,34,2.2,110,5200,2665,15.6,184,103,68,2785
13,14,13.4,15.1,16.8,19,28,3.4,160,4600,1805,15.5,193,101,74,3240
14,15,13.4,15.9,18.4,21,29,2.2,110,5200,2595,16.5,198,108,71,3195
15,16,14.7,16.3,18.0,18,23,3.8,170,4800,1690,20.0,178,110,74,3715
16,17,14.7,16.6,18.6,15,20,4.3,165,4000,1790,27.0,194,111,78,4025
17,18,18.0,18.8,19.6,17,26,5.0,170,4200,1350,23.0,214,116,77,3910
18,19,34.6,38.0,41.5,17,25,5.7,300,5000,1450,20.0,179,96,74,3380
19,20,18.4,18.4,18.4,20,28,3.3,153,5300,1990,18.0,203,113,74,3515
20,21,14.5,15.8,17.1,23,28,3.0,141,5000,2090,16.0,183,104,68,3085
21,22,29.5,29.5,29.5,20,26,3.3,147,4800,1785,16.0,203,110,69,3570
22,23,7.9,9.2,10.6,29,33,1.5,92,6000,3285,13.2,174,98,66,2270
23,24,8.4,11.3,14.2,23,29,2.2,93,4800,2595,14.0,172,97,67,2670
24,25,11.9,13.3,14.7,22,27,2.5,100,4800,2535,16.0,181,104,68,2970
25,26,13.6,19.0,24.4,17,21,3.0,142,5000,1970,20.0,175,112,72,3705
26,27,14.8,15.6,16.4,21,27,2.5,100,4800,2465,16.0,192,105,69,3080
27,28,18.5,25.8,33.1,18,24,3.0,300,6000,2120,19.8,180,97,72,3805
28,29,7.9,12.2,16.5,29,33,1.5,92,6000,2505,13.2,174,98,66,2295
29,30,17.5,19.3,21.2,20,28,3.5,214,5800,1980,18.0,202,113,74,3490

In [60]:
cars.tail()

,Unnamed: 0,Min.Price,Price,Max.Price,MPG.city,MPG.highway,EngineSize,Horsepower,RPM,Rev.per.mile,Fuel.tank.capacity,Length,Wheelbase,Width,Weight
88,89,16.6,19.7,22.7,17,21,2.5,109,4500,2915,21.1,187,115,72,3960
89,90,17.6,20.0,22.4,21,30,2.0,134,5800,2685,18.5,180,103,67,2985
90,91,22.9,23.3,23.7,18,25,2.8,178,5800,2385,18.5,159,97,66,2810
91,92,21.8,22.7,23.5,21,28,2.3,114,5400,2215,15.8,190,104,67,2985
92,93,24.8,26.7,28.5,20,28,2.4,168,6200,2310,19.3,184,105,69,3245

In [61]:
cars.columns

Index(['Unnamed: 0', 'Min.Price', 'Price', 'Max.Price', 'MPG.city',
       'MPG.highway', 'EngineSize', 'Horsepower', 'RPM', 'Rev.per.mile',
       'Fuel.tank.capacity', 'Length', 'Wheelbase', 'Width', 'Weight'],
      dtype='object')

In [73]:
cars.corr()

,Unnamed: 0,Min.Price,Price,Max.Price,MPG.city,MPG.highway,EngineSize,Horsepower,RPM,Rev.per.mile,Fuel.tank.capacity,Length,Wheelbase,Width,Weight
Unnamed: 0,1.000000,-0.144463,-0.137277,-0.126567,0.161808,0.137317,-0.338286,-0.233012,0.167772,0.226389,-0.179034,-0.277911,-0.244888,-0.293592,-0.220525
Min.Price,-0.144463,1.000000,0.970601,0.906756,-0.622875,-0.579966,0.645488,0.802444,-0.042598,-0.470395,0.635369,0.553859,0.516758,0.492878,0.666554
Price,-0.137277,0.970601,1.000000,0.981580,-0.594562,-0.560680,0.597425,0.788218,-0.004955,-0.426395,0.619480,0.503628,0.500864,0.456028,0.647179
Max.Price,-0.126567,0.906756,0.981580,1.000000,-0.547811,-0.522561,0.535012,0.744445,0.025015,-0.374024,0.581294,0.442933,0.467501,0.408414,0.605142
MPG.city,0.161808,-0.622875,-0.594562,-0.547811,1.000000,0.943936,-0.710003,-0.672636,0.363045,0.695857,-0.813144,-0.666239,-0.667108,-0.720534,-0.843139
MPG.highway,0.137317,-0.579966,-0.560680,-0.522561,0.943936,1.000000,-0.626795,-0.619044,0.313469,0.587497,-0.786039,-0.542897,-0.615384,-0.640359,-0.810658
EngineSize,-0.338286,0.645488,0.597425,0.535012,-0.710003,-0.626795,1.000000,0.732120,-0.547898,-0.824009,0.759306,0.780283,0.732484,0.867110,0.845075
Horsepower,-0.233012,0.802444,0.788218,0.744445,-0.672636,-0.619044,0.732120,1.000000,0.036688,-0.600314,0.711790,0.550865,0.486854,0.644413,0.738798
RPM,0.167772,-0.042598,-0.004955,0.025015,0.363045,0.313469,-0.547898,0.036688,1.000000,0.494764,-0.333345,-0.441249,-0.467812,-0.539721,-0.427931
Rev.per.mile,0.226389,-0.470395,-0.426395,-0.374024,0.695857,0.587497,-0.824009,-0.600314,0.494764,1.000000,-0.609710,-0.690233,-0.636824,-0.780460,-0.735264
Fuel.tank.capacity,-0.179034,0.635369,0.619480,0.581294,-0.813144,-0.786039,0.759306,0.711790,-0.333345,-0.609710,1.000000,0.690461,0.757674,0.798719,0.894018
Length,-0.277911,0.553859,0.503628,0.442933,-0.666239,-0.542897,0.780283,0.550865,-0.441249,-0.690233,0.690461,1.000000,0.823650,0.822148,0.806274
Wheelbase,-0.244888,0.516758,0.500864,0.467501,-0.667108,-0.615384,0.732484,0.486854,-0.467812,-0.636824,0.757674,0.823650,1.000000,0.807213,0.871895
Width,-0.293592,0.492878,0.456028,0.408414,-0.720534,-0.640359,0.867110,0.644413,-0.539721,-0.780460,0.798719,0.822148,0.807213,1.000000,0.874961
Weight,-0.220525,0.666554,0.647179,0.605142,-0.843139,-0.810658,0.845075,0.738798,-0.427931,-0.735264,0.894018,0.806274,0.871895,0.874961,1.000000

In [63]:
x=cars
y=cars["Price"]

In [69]:
model=LinearRegression()
model.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [71]:
model.score(x,y)

1.0

In [74]:
cars.corr().max()

Unnamed: 0            1.0
Min.Price             1.0
Price                 1.0
Max.Price             1.0
MPG.city              1.0
MPG.highway           1.0
EngineSize            1.0
Horsepower            1.0
RPM                   1.0
Rev.per.mile          1.0
Fuel.tank.capacity    1.0
Length                1.0
Wheelbase             1.0
Width                 1.0
Weight                1.0
dtype: float64